apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosaic-ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosaic-ping
  template:
    metadata:
      labels:
        app: mosaic-ping
    spec:
      containers:
        - name: mosaic-ping
          image: mosaic-ping:latest
          args: ["--hosts=8.8.8.8,1.1.1.1,localhost"]
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              add: ["NET_RAW"]
---
apiVersion: v1
kind: Service
metadata:
  name: mosaic-ping
spec:
  type: NodePort
  selector:
    app: mosaic-ping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
