name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          # Create build directory
          mkdir -p build
          
          # Windows
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o build/mosaic.exe .
          
          # macOS
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o build/mosaic-mac-amd64 .
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o build/mosaic-mac-arm64 .
          
          # Linux
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/mosaic-linux-amd64 .
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o build/mosaic-linux-arm64 .

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosaic.exe
          path: build/mosaic.exe

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with: 
          name: mosaic-mac-amd64
          path: build/mosaic-mac-amd64

      - name: Upload macOS arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosaic-mac-arm64
          path: build/mosaic-mac-arm64

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosaic-linux-amd64
          path: build/mosaic-linux-amd64

      - name: Upload Linux arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosaic-linux-arm64
          path: build/mosaic-linux-arm64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            ./artifacts/**/mosaic.exe
            ./artifacts/**/mosaic-mac-amd64
            ./artifacts/**/mosaic-mac-arm64
            ./artifacts/**/mosaic-linux-amd64
            ./artifacts/**/mosaic-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RELEASE }}