name: Docker CI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: piterpentester/mosaic

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make docker-build-push
        run: make docker-build-push TAG=${{ github.ref_name }}
        env:
          DOCKER_USERNAME: piterpentester
          DOCKER_PASSWORD: ${{ secrets.PAT_RELEASE }}
