name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o mosaic.exe main.go
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o mosaic-mac-amd64 main.go
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o mosaic-mac-arm64 main.go
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o mosaic-linux-amd64 main.go
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o mosaic-linux-arm64 main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosaic-binaries
          path: |
            ./mosaic.exe
            ./mosaic-mac-amd64
            ./mosaic-mac-arm64
            ./mosaic-linux-amd64
            ./mosaic-linux-arm64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/**/mosaic-amd64
            ./artifacts/**/mosaic-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RELEASE }}