name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          if [[ "${{ matrix.goarch }}" == "windows/amd64" ]]; then
            GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o mosaic.exe main.go
          elif [[ "${{ matrix.goarch }}" == "darwin/amd64" ]]; then
            GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o mosaic main.go
          elif [[ "${{ matrix.goarch }}" == "darwin/arm64" ]]; then
            GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o mosaic main.go
          else
            GOOS=linux GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -o mosaic-${{ matrix.goarch }} main.go
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosaic-${{ matrix.goarch }}
          path: |
            {{#if (eq matrix.goarch 'windows/amd64')}}
              mosaic.exe
            {{else}}
              mosaic-${{ matrix.goarch }}
            {{/if}}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/**/mosaic-amd64
            ./artifacts/**/mosaic-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RELEASE }}