name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          GOOS=linux GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -o mosaic-${{ matrix.goarch }} main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosaic-${{ matrix.goarch }}
          path: mosaic-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/**/mosaic-amd64
            ./artifacts/**/mosaic-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RELEASE }}